// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.20;

import "forge-std/Script.sol";

/**
 * @title  DeployStarkVerifier
 * @notice Deploys the StarkWare mainnet `starknet` (layout 6, 7 builtins)
 *         on-chain STARK verifier stack from source vendored under
 *         contracts/lib/starkware-mainnet/.
 *
 *         These contracts are Sourcify-verified mainnet source, byte-for-byte
 *         (modulo metadata) what's deployed at:
 *
 *           GpsStatementVerifier    0x9fb7F48dCB26b7bFA4e580b2dEFf637B13751942
 *           CpuFrilessVerifier (id=6) 0xe155154845950573ec5f518fc0d4950ab71303ff
 *           CairoBootloaderProgram  (own; built from cairo-bootloader's
 *                                    keccak-stripped 7-builtin bootloader)
 *
 *         stark-evm-adapter targets cairoVerifierId=6 by default and its
 *         annotated_proof.json fixture uses layout="starknet" (7 builtins
 *         -- output, pedersen, range_check, ecdsa, bitwise, ec_op, poseidon).
 *         This deploy mirrors that configuration so a proof generated by
 *         our prover-api against layout=starknet, wrapped in our
 *         keccak-stripped bootloader, is accepted unchanged.
 *
 * Layout 6 selectedBuiltins (LayoutSpecific.sol.getLayoutInfo):
 *   output, pedersen, range_check, ecdsa, bitwise, ec_op, poseidon.
 *
 * Layout 6 auxPolynomials[] index map (LayoutSpecific.sol.initPeriodicColumns):
 *   [0] CpuConstraintPoly
 *   [1] PedersenPointsX
 *   [2] PedersenPointsY
 *   [3] EcdsaGeneratorPointsX
 *   [4] EcdsaGeneratorPointsY
 *   [5] PoseidonFullRoundKey0
 *   [6] PoseidonFullRoundKey1
 *   [7] PoseidonFullRoundKey2
 *   [8] PoseidonPartialRoundKey0
 *   [9] PoseidonPartialRoundKey1
 */
contract DeployStarkVerifier is Script {
    struct Deployment {
        // Aux polynomials (10 leaf contracts).
        address cpuConstraintPoly;
        address pedersenX;
        address pedersenY;
        address ecdsaX;
        address ecdsaY;
        address poseidonFR0;
        address poseidonFR1;
        address poseidonFR2;
        address poseidonPR0;
        address poseidonPR1;
        // OODS evaluator.
        address cpuOods;
        // Fact registries.
        address memoryPageFactRegistry;
        address merkleStatementContract;
        address friStatementContract;
        // CPU + bootloader.
        address cpuFrilessVerifier;
        address cairoBootloaderProgram;
        // Public entry point.
        address gpsStatementVerifier;
    }

    function run() external returns (Deployment memory d) {
        uint256 simpleBootloaderHash = _envOrZero("SIMPLE_BOOTLOADER_HASH");
        uint256 hashedCairoVerifiers = _envOrZero("HASHED_CAIRO_VERIFIERS");

        vm.startBroadcast();

        // ── 1. Periodic columns ───────────────────────────────────────
        d.cpuConstraintPoly = vm.deployCode("layout6/CpuConstraintPoly.sol:CpuConstraintPoly");
        d.pedersenX         = vm.deployCode("PedersenHashPointsXColumn.sol:PedersenHashPointsXColumn");
        d.pedersenY         = vm.deployCode("PedersenHashPointsYColumn.sol:PedersenHashPointsYColumn");
        d.ecdsaX            = vm.deployCode("EcdsaPointsXColumn.sol:EcdsaPointsXColumn");
        d.ecdsaY            = vm.deployCode("EcdsaPointsYColumn.sol:EcdsaPointsYColumn");
        d.poseidonFR0       = vm.deployCode("layout6/PoseidonPoseidonFullRoundKey0Column.sol:PoseidonPoseidonFullRoundKey0Column");
        d.poseidonFR1       = vm.deployCode("layout6/PoseidonPoseidonFullRoundKey1Column.sol:PoseidonPoseidonFullRoundKey1Column");
        d.poseidonFR2       = vm.deployCode("layout6/PoseidonPoseidonFullRoundKey2Column.sol:PoseidonPoseidonFullRoundKey2Column");
        d.poseidonPR0       = vm.deployCode("layout6/PoseidonPoseidonPartialRoundKey0Column.sol:PoseidonPoseidonPartialRoundKey0Column");
        d.poseidonPR1       = vm.deployCode("layout6/PoseidonPoseidonPartialRoundKey1Column.sol:PoseidonPoseidonPartialRoundKey1Column");

        console2.log("Periodic columns (layout 6 / starknet):");
        console2.log("  CpuConstraintPoly:    ", d.cpuConstraintPoly);
        console2.log("  PedersenX:            ", d.pedersenX);
        console2.log("  PedersenY:            ", d.pedersenY);
        console2.log("  EcdsaX:               ", d.ecdsaX);
        console2.log("  EcdsaY:               ", d.ecdsaY);
        console2.log("  PoseidonFR0:          ", d.poseidonFR0);
        console2.log("  PoseidonFR1:          ", d.poseidonFR1);
        console2.log("  PoseidonFR2:          ", d.poseidonFR2);
        console2.log("  PoseidonPR0:          ", d.poseidonPR0);
        console2.log("  PoseidonPR1:          ", d.poseidonPR1);

        // ── 2. OODS evaluator ─────────────────────────────────────────
        d.cpuOods = vm.deployCode("layout6/CpuOods.sol:CpuOods");
        console2.log("CpuOods (layout6):      ", d.cpuOods);

        // ── 3. Fact registries ────────────────────────────────────────
        d.memoryPageFactRegistry  = vm.deployCode("MemoryPageFactRegistry.sol:MemoryPageFactRegistry");
        d.merkleStatementContract = vm.deployCode("MerkleStatementContract.sol:MerkleStatementContract");
        d.friStatementContract    = vm.deployCode("FriStatementContract.sol:FriStatementContract");
        console2.log("MemoryPageFactRegistry: ", d.memoryPageFactRegistry);
        console2.log("MerkleStatementContract:", d.merkleStatementContract);
        console2.log("FriStatementContract:   ", d.friStatementContract);

        // ── 4. CPU verifier (layout 6) ────────────────────────────────
        address[] memory auxPolynomials = new address[](10);
        auxPolynomials[0] = d.cpuConstraintPoly;
        auxPolynomials[1] = d.pedersenX;
        auxPolynomials[2] = d.pedersenY;
        auxPolynomials[3] = d.ecdsaX;
        auxPolynomials[4] = d.ecdsaY;
        auxPolynomials[5] = d.poseidonFR0;
        auxPolynomials[6] = d.poseidonFR1;
        auxPolynomials[7] = d.poseidonFR2;
        auxPolynomials[8] = d.poseidonPR0;
        auxPolynomials[9] = d.poseidonPR1;

        d.cpuFrilessVerifier = vm.deployCode(
            "layout6/CpuFrilessVerifier.sol:CpuFrilessVerifier",
            abi.encode(
                auxPolynomials,
                d.cpuOods,
                d.memoryPageFactRegistry,
                d.merkleStatementContract,
                d.friStatementContract,
                // numSecurityBits: relaxed from mainnet's 80 to 40 for our
                // PoC. Our prover-api emits proofs with 16 queries x 2 cosets +
                // 30 PoW bits = 62 effective security bits. Setting the gate
                // to 40 leaves 22 bits of headroom while keeping a meaningful
                // soundness floor (an adversary still needs 2^40 work).
                // Tighten to 80 for production (matches mainnet).
                uint256(40),
                uint256(30)
            )
        );
        console2.log("CpuFrilessVerifier (layout6):", d.cpuFrilessVerifier);

        // ── 5. Bootloader program ─────────────────────────────────────
        d.cairoBootloaderProgram = vm.deployCode("CairoBootloaderProgram.sol:CairoBootloaderProgram");
        console2.log("CairoBootloaderProgram: ", d.cairoBootloaderProgram);

        // ── 6. GpsStatementVerifier ───────────────────────────────────
        // Mainnet GPS constructor (7 args, includes referenceVerifier slot).
        // cairoVerifierContracts array: 8 entries with our starknet verifier
        // at index 6 (canonical mapping mainnet uses; stark-evm-adapter
        // hardcodes cairoVerifierId=6).
        address[] memory cairoVerifiers = new address[](8);
        for (uint256 i = 0; i < 8; i++) {
            cairoVerifiers[i] = address(0);
        }
        cairoVerifiers[6] = d.cpuFrilessVerifier;

        d.gpsStatementVerifier = vm.deployCode(
            "GpsStatementVerifier.sol:GpsStatementVerifier",
            abi.encode(
                d.cairoBootloaderProgram,
                d.memoryPageFactRegistry,
                cairoVerifiers,
                hashedCairoVerifiers,
                simpleBootloaderHash,
                address(0),    // referenceVerifier disabled
                uint256(0)     // referralDuration disabled
            )
        );
        console2.log("GpsStatementVerifier:   ", d.gpsStatementVerifier);

        vm.stopBroadcast();

        console2.log("");
        console2.log("===== StarkWare mainnet `starknet` (layout 6) deployment =====");
        console2.log("GpsStatementVerifier (set STARK_VERIFIER_ADDR to this):");
        console2.log("  ", d.gpsStatementVerifier);
        console2.log("cairoVerifierId: 6");
    }

    function _envOrZero(string memory key) internal view returns (uint256) {
        try vm.envUint(key) returns (uint256 v) {
            return v;
        } catch {
            return 0;
        }
    }
}
